apiVersion: v1
baseDomain: paas.nxtg.cloudcenter.corp
proxy:
  httpProxy: http://10.220.255.10:8080
  httpsProxy: http://10.220.255.10:8080
  noProxy: cccvng0vcenc004.vcf04.nxtg.cloudcenter.corp,10.0.0.0/8,49.0.0.0/8,85.0.0.0/8,107.0.0.0/12,172.16.0.0/12,180.0.0.0/8,10.120.0.0/13,10.112.0.0/13,apps.ocp01.paas.nxtg.cloudcenter.corp,ocp01.paas.nxtg.cloudcenter.corp,172.31.0.0/16
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp01
networking:
  clusterNetwork:
  - cidr: 10.116.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.226.46.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.31.0.0/16
platform:
  vsphere:
    apiVIP: 10.226.46.6
    cluster: C3CLNG1COMP004
    datacenter: COMP04
    folder: /COMP04/vm/ocp01/
    defaultDatastore: c3clng1comp004_datastore13
    ingressVIP: 10.226.46.22
    network: PAAS-Cluster1-OCP
    #network: /COMP04/host/C3CLNG1COMP004/cccxng1esxi303.vcf04.nxtg.cloudcenter.corp/PAAS-Cluster1-OCP
    password: P3r1qu1t0!
    username: administrator@vsphere.local
    vCenter: cccvng0vcenc004.vcf04.nxtg.cloudcenter.corp
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2VzX2dzeXNfc2lzdHJhbnMxcm5tdXVlcHZrdzQ3MWJyaDc1dm1udmFyZjg6MVFWRDdCUlVNQ1RRQkY1OFE3RTMyQUdaRzE4UUFFRFBZMFhWR0ZZT0lQV1BSS0JGQldPVVFUNEtHMDUySFlNQQ==","email":"global_paas@produban.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2VzX2dzeXNfc2lzdHJhbnMxcm5tdXVlcHZrdzQ3MWJyaDc1dm1udmFyZjg6MVFWRDdCUlVNQ1RRQkY1OFE3RTMyQUdaRzE4UUFFRFBZMFhWR0ZZT0lQV1BSS0JGQldPVVFUNEtHMDUySFlNQQ==","email":"global_paas@produban.com"},"registry.connect.redhat.com":{"auth":"NjYwNDIzN3x1aGMtMVJuTXVVRVB2a3c0NzFCUkg3NVZtTlZBckY4OmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKaFpXTTFPRGszTkdFeE4yVTBZVGMwT0dNek1XSXdObVExWXpFME16Z3daaUo5LmFjaVd2ckN0dkNIX3JQMUZGZ2pyQUhFNUtNdHNmTkxaSUlPTGtjc3FyRTIwWmI2NkhnSlgyTzhVVWNwQTk0N3hLQUxuSnJhMnA4X1RwN0FPcFctVjRYOGhrZDFPMmZwb1A2alBheFlLdkRNNlZob0hJYXdyTERhUDhSWVlvQjRlTXJfVG5lazlRcGZrMElsc1JVUmpwMDUwbDFJeGIzRTJVSFpkVVg1emNDM2lGSC1FNGxfcTBpdzdabHRmakMxOVIzWDVaVHh1OVN3V2YwMWdzNG1wX3FLU1hiUXJqRjFFMTFhZXhxOWhTQjNXTk9HOVdGOFV1dU9jR09vUEZlOGZVelgxSHRFUUdyQWlCdTlmc0RsejgxaV81VEZ2VU54OUV5OXlaM2RzNTdzVWpvbVVtcGxTRW83YWZYbzFvZEJSMVNOZGJxZkQzVnRpNVZDRjJUY0VYaTZTS0RuSWNsLXYxOHlTUlc4UU40akJ2azdaQzVnT2tfOGY2T0pJLVRlcU1FaFVhVnlKeklTRW5tVmt3U29iQ2x4TTh0VlVpcFZvQnRGTXV1eXkwNmhxemI4U3lzQ3pqM0hXSTgzWmhySVpnQmRXQnNxdnBfbzZ4a2ZoWm1tVzRxZWduZWhINE5sNnh6Q3BHZ01yeUdNV1NNczludGtsb215eXVXb01vUTN5ZXprTFNIVHhFLW1lajNfV1c2dEZzZ2FNT3V0X3JfakdDZGd1VDRxelFEWEQ0MGM2N2xHbjdwUDNlR2hXaFM0Z2pKaDZkTEJkcFYxV2JlTFRTRXdxX3U4RlJyLUZWQ19vRnVURmE2dU55UjVEQkxqbkMzUjFVQkU2RDg1MkxYY1lVeGR1TE1kXzVDQzZ2VTZpbjBWaURHMllHRkNMOXJjT09qbGFYWkdzOVlB","email":"global_paas@produban.com"},"registry.redhat.io":{"auth":"NjYwNDIzN3x1aGMtMVJuTXVVRVB2a3c0NzFCUkg3NVZtTlZBckY4OmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lKaFpXTTFPRGszTkdFeE4yVTBZVGMwT0dNek1XSXdObVExWXpFME16Z3daaUo5LmFjaVd2ckN0dkNIX3JQMUZGZ2pyQUhFNUtNdHNmTkxaSUlPTGtjc3FyRTIwWmI2NkhnSlgyTzhVVWNwQTk0N3hLQUxuSnJhMnA4X1RwN0FPcFctVjRYOGhrZDFPMmZwb1A2alBheFlLdkRNNlZob0hJYXdyTERhUDhSWVlvQjRlTXJfVG5lazlRcGZrMElsc1JVUmpwMDUwbDFJeGIzRTJVSFpkVVg1emNDM2lGSC1FNGxfcTBpdzdabHRmakMxOVIzWDVaVHh1OVN3V2YwMWdzNG1wX3FLU1hiUXJqRjFFMTFhZXhxOWhTQjNXTk9HOVdGOFV1dU9jR09vUEZlOGZVelgxSHRFUUdyQWlCdTlmc0RsejgxaV81VEZ2VU54OUV5OXlaM2RzNTdzVWpvbVVtcGxTRW83YWZYbzFvZEJSMVNOZGJxZkQzVnRpNVZDRjJUY0VYaTZTS0RuSWNsLXYxOHlTUlc4UU40akJ2azdaQzVnT2tfOGY2T0pJLVRlcU1FaFVhVnlKeklTRW5tVmt3U29iQ2x4TTh0VlVpcFZvQnRGTXV1eXkwNmhxemI4U3lzQ3pqM0hXSTgzWmhySVpnQmRXQnNxdnBfbzZ4a2ZoWm1tVzRxZWduZWhINE5sNnh6Q3BHZ01yeUdNV1NNczludGtsb215eXVXb01vUTN5ZXprTFNIVHhFLW1lajNfV1c2dEZzZ2FNT3V0X3JfakdDZGd1VDRxelFEWEQ0MGM2N2xHbjdwUDNlR2hXaFM0Z2pKaDZkTEJkcFYxV2JlTFRTRXdxX3U4RlJyLUZWQ19vRnVURmE2dU55UjVEQkxqbkMzUjFVQkU2RDg1MkxYY1lVeGR1TE1kXzVDQzZ2VTZpbjBWaURHMllHRkNMOXJjT09qbGFYWkdzOVlB","email":"global_paas@produban.com"}}}'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIEBjCCAu6gAwIBAgIUDyB7kES3m4j2A9ooDexU2K3cazUwDQYJKoZIhvcNAQEL
  BQAwgYkxCzAJBgNVBAYTAkVTMQ8wDQYDVQQIDAZNYWRyaWQxDzANBgNVBAcMBk1h
  ZHJpZDEMMAoGA1UECgwDQ0NDMQwwCgYDVQQLDANDQ0MxPDA6BgNVBAMMM3JoY29z
  LXJlZGlyZWN0b3IuYXBwcy5hcnQueHExYy5wMS5vcGVuc2hpZnRhcHBzLmNvbTAe
  Fw0yMjA2MjQwNzQwMDhaFw0yNDA2MjMwNzQwMDhaMIGJMQswCQYDVQQGEwJFUzEP
  MA0GA1UECAwGTWFkcmlkMQ8wDQYDVQQHDAZNYWRyaWQxDDAKBgNVBAoMA0NDQzEM
  MAoGA1UECwwDQ0NDMTwwOgYDVQQDDDNyaGNvcy1yZWRpcmVjdG9yLmFwcHMuYXJ0
  LnhxMWMucDEub3BlbnNoaWZ0YXBwcy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IB
  DwAwggEKAoIBAQClLGdkPtfr+hhvdkr7RfjVgaxJms6MTNBf1Ju3d6zQGr9FsRag
  29ULXHO2aI5tRSIoKkeHRFhfq6k2Q6WahBlWourf2bBjODGykFY0JW2n9CYcc3YZ
  l5NtZmYvjrfYE+INGFDPj7V3qtbzGfelJ3EhOs+/N5RpmhTbe9FQFvUywuxnB5F5
  ZnQfBOHkb10gZRuVavGzwT4oCvWPFOOU+g5I1WwBghYsdTZ40ChH3il9e2caIcNC
  fnN3Ezrrg8F0H0z3tUrFF6k+sJAt4C3OGs4fQLvH1uDgT5n5VqoQq/vhCsuDLWOl
  yowS2bvd5jPlsDHs7NVq2cLPDYazBvxyyhLTAgMBAAGjZDBiMAsGA1UdDwQEAwIB
  tjATBgNVHSUEDDAKBggrBgEFBQcDATA+BgNVHREENzA1gjNyaGNvcy1yZWRpcmVj
  dG9yLmFwcHMuYXJ0LnhxMWMucDEub3BlbnNoaWZ0YXBwcy5jb20wDQYJKoZIhvcN
  AQELBQADggEBAJje1+tVBX6e8b60fjvwf9bkNNOasEWIHx6tOKejGFWW8wqa9H+d
  GTAn40dzBEQhZSvo+uO3/20iincOaAxSsR+Q+UmQ84uyj/fm/Dc3l9D+p9bg5gDz
  XWbj7Gl1VDDjeFZ0T1glgBSaM9at0f2hja42UJBjNr0Q1TxZKALlNpIP0ke+FwTB
  2OdY7EKKJLq3FdUNw3os2p6JiXzW5kEcEepAsQc78JS+FWWgN2uGRCYij5ZoUIxq
  SvMqm0cLW3XKutNei05hwvaZSoWb1xZVRwqNEWjQpozX4ZVyVGXW4s3WM9cjUGIp
  6x0JyEi3koqtFC13wkRJuwZo90Njs15mhzs=
  -----END CERTIFICATE-----
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPZMFyD4dRufLErPdYODSZ0FP70lrTqh30XCtJLhUe+G root@ccclstgpaasd001.stng.cloudcenter.corp

